### ISSUE TITLE
ROLI Dashboard 4.3.0 update disables metadata scripts

### ISSUE THREAD

**Issue by anthonyalfimov** [anthonyalfimov/SWONIC-Dynamic-Controls#65]
After installing the 4.3.0 update, metadata variable change scripts don't function anymore, which breaks the apps Dashboard UI.

**Comment by anthonyalfimov** [comment]
This has been confirmed as a bug by ROLI.

**Comment by anthonyalfimov** [comment]
Fixed in Dashboard 4.3.1 on Mac. I will confirm if it is fixed on Win as well.

**Comment by SWONIC** [comment]
I can confirm this!

**Comment by anthonyalfimov** [comment]
Fixed in Dashboard 4.3.1 on Win.
